version: "3.2"
services:

  redis:
    image: redis:latest
  
  api:
    build:
      context: ./api
    command: passenger start
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./api:/api

  sidekiq: 
    build:
      context: ./api
    command: bundle exec sidekiq -r ./app/routes.rb
    depends_on:
      - redis
    volumes:
      - ./api:/api
    environment:
      WIRED_REMINDER_MAIL_ADDRESS:
      WIRED_REMINDER_MAIL_PORT:
      WIRED_REMINDER_MAIL_USER:
      WIRED_REMINDER_MAIL_PASSWORD:
      WIRED_REMINDER_MAIL_DOMAIN:
